version: 2.1

orbs:
  heroku: circleci/heroku@0.0.6

commands:
  cargo:
    description: "Run cargo command with specific Rust version"
    parameters:
      command:
        type: string
      rust_channel:
        type: string
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: << parameters.command >> all targets
          command: cargo << parameters.command >> --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}
  rust_check:
    description: "Run cargo check workflow with specific Rust version"
    parameters:
      rust_channel:
        type: string
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo check --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}
  rust_build:
    description: "Run cargo build workflow with specific Rust version"
    parameters:
      rust_channel:
        type: string
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}
  rust_test:
    description: "Run cargo test workflow with specific Rust version"
    parameters:
      rust_channel:
        type: string
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test --all
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}


jobs:
  check-1-34:
    docker:
      - image: rust:1.34
    steps:
      - cargo:
          command: check
          rust_channel: 1-34
  check-stable:
    docker:
      - image: rust:latest
    steps:
      - rust_check:
          rust_channel: stable
  check-nightly:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - rust_check:
          rust_channel: nightly
  build-1-34:
    docker:
      - image: rust:1.34
    steps:
      - cargo:
          command: build
          rust_channel: 1-34
  build-stable:
    docker:
      - image: rust:latest
    steps:
      - rust_build:
          rust_channel: stable
  build-nightly:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - rust_build:
          rust_channel: nightly
  test-1-34:
    docker:
      - image: rust:1.34
    steps:
      - cargo:
          command: test
          rust_channel: 1-34
  test-stable:
    docker:
      - image: rust:latest
    steps:
      - rust_test:
          rust_channel: stable
  test-nightly:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - rust_test:
          rust_channel: nightly


check-build-test: &check-build-test
  - check-1-34
  - build-1-34:
      requires:
        - check-1-34
  - test-1-34:
      requires:
        - build-1-34
  - check-stable
  - build-stable:
      requires:
        - check-stable
  - test-stable:
      requires:
        - build-stable
  - check-nightly
  - build-nightly:
      requires:
        - check-nightly
  - test-nightly:
      requires:
        - build-nightly


workflows:
  version: 2
  build:
    jobs:
      *check-build-test
  cron:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      *check-build-test

