version: 2.1

orbs:
  heroku: circleci/heroku@0.0.6

commands:
  rust_build:
    description: "Run cargo build workflow with specific Rust version"
    parameters:
      rust_channel:
        type: string
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - run:
          name: Run all tests
          command: cargo test --all
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}


jobs:
  build-1-34:
    docker:
      - image: rust:1.34
    steps:
      - rust_build:
          rust_channel: 1-34
  build-stable:
    docker:
      - image: rust:latest
    steps:
      - rust_build:
          rust_channel: stable
  build-nightly:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - rust_build:
          rust_channel: nightly


workflows:
  version: 2
  build:
    jobs:
      - build-1-34
      - build-stable
      - build-nightly
  cron:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-1-34
      - build-stable
      - build-nightly

